### ISSUE TITLE
Is it working and can I contribute and use it for a fitness challange with my group 

### ISSUE THREAD

**Issue by kanumuri9593** [johnt84/StravaClubStats#13]
hi would like to know how i can leverage this project, currently its giving 404

**Comment by johnt84** [comment]
Hi, sorry for the delay in reply.  Just read this message.

It should be online now.  It might have been giving a 404 as my Azure Dev Profile had possibly ran out of credits when you tried it.

Yeah you can certainly contribute.  If you submit a PR I'll take a look at it. :)
